"""Add unique constraint

Revision ID: 0d2e20be1fc3
Revises: fe9044f09312
Create Date: 2026-08-11 22:59:05.294234

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d2e20be1fc3"
down_revision: str | Sequence[str] | None = "fe9044f09312"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation_events", sa.Column("request_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_conversation_events_request_id"),
        "conversation_events",
        ["request_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_conversation_event_request_role",
        "conversation_events",
        ["conversation_id", "request_id", "role"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_conversation_event_request_role", "conversation_events", type_="unique")
    op.drop_index(op.f("ix_conversation_events_request_id"), table_name="conversation_events")
    op.drop_column("conversation_events", "request_id")
    # ### end Alembic commands ###
