"""init HITL models

Revision ID: 2a5253e02911
Revises: 0d2e20be1fc3
Create Date: 2026-08-21 23:57:46.438029

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a5253e02911"
down_revision: str | Sequence[str] | None = "0d2e20be1fc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actions",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "GENERAL",
                "READ",
                "ANALYZE",
                "GENERATE",
                "UPDATE",
                "DELETE",
                "SEND",
                "SUBMIT",
                "EXTERNAL",
                name="action_type",
            ),
            nullable=False,
        ),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=True),
        sa.Column("target_agent_id", sa.String(length=255), nullable=True),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=10000), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["conversation_events.id"],
            name=op.f("fk_actions_event_id_conversation_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
    )
    op.create_index(op.f("ix_actions_action_type"), "actions", ["action_type"], unique=False)
    op.create_index(op.f("ix_actions_agent_id"), "actions", ["agent_id"], unique=False)
    op.create_index(op.f("ix_actions_event_id"), "actions", ["event_id"], unique=False)
    op.create_index(op.f("ix_actions_resource_id"), "actions", ["resource_id"], unique=False)
    op.create_index(
        op.f("ix_actions_target_agent_id"), "actions", ["target_agent_id"], unique=False
    )
    op.create_index(op.f("ix_actions_tool_name"), "actions", ["tool_name"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("action_id", sa.String(length=64), nullable=False),
        sa.Column("action_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("requested_by", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_REQUIRED",
                "WAITING",
                "APPROVED",
                "REJECTED",
                "EDITED",
                "EXPIRED",
                name="approval_status",
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"], ["actions.id"], name=op.f("fk_approvals_action_id_actions")
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_approvals_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(op.f("ix_approvals_action_id"), "approvals", ["action_id"], unique=False)
    op.create_index(op.f("ix_approvals_expires_at"), "approvals", ["expires_at"], unique=False)
    op.create_index(op.f("ix_approvals_requested_by"), "approvals", ["requested_by"], unique=False)
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_requested_by"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_expires_at"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_action_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_actions_tool_name"), table_name="actions")
    op.drop_index(op.f("ix_actions_target_agent_id"), table_name="actions")
    op.drop_index(op.f("ix_actions_resource_id"), table_name="actions")
    op.drop_index(op.f("ix_actions_event_id"), table_name="actions")
    op.drop_index(op.f("ix_actions_agent_id"), table_name="actions")
    op.drop_index(op.f("ix_actions_action_type"), table_name="actions")
    op.drop_table("actions")
    # ### end Alembic commands ###
