"""
Action application service.
"""

from __future__ import annotations

from src.core.dto.action import ActionRequestDTO, ActionResponseDTO
from src.repositories.action import ActionRepository


class ActionService:
    """
    Application service for persisted actions.

    This service owns action creation and retrieval.
    Authorization and approval decisions remain outside
    this service.
    """

    def __init__(
        self,
        *,
        repository: ActionRepository,
    ) -> None:
        self._repository = repository

    async def create(
        self,
        *,
        event_id: str,
        action: ActionRequestDTO,
    ) -> ActionResponseDTO:
        """
        Create and persist an action for a conversation event.

        The action ID is generated by the persistence layer.
        """

        return await self._repository.create(
            event_id=event_id,
            action=action,
        )

    async def get(
        self,
        action_id: str,
    ) -> ActionResponseDTO:
        """
        Retrieve a persisted action by ID.
        """

        action = await self._repository.get(
            action_id,
        )

        if action is None:
            raise LookupError(
                f"Action not found: {action_id}",
            )

        return action
