"""
Shared pytest fixtures available to every test module.

Fixtures
--------
db_engine       Session-scoped SQLite engine (creates tables once)
db_session      Function-scoped session with automatic rollback
client          FastAPI TestClient wired to the test DB
mock_embeddings Deterministic fake embedding model
mock_llm        Fake LLM provider that returns canned answers
mock_storage    In-memory storage (no disk I/O)
mock_cache      MemoryCache instance
sample_pdf_path Path to a tiny test PDF written at session start
"""

from __future__ import annotations

from collections.abc import AsyncIterator, Generator

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

from src.core.config import settings
from src.core.enums import Environment
from src.db.base import Base
from src.db.session import get_db_session

# ── Override config for tests ───

settings.ENVIRONMENT = Environment.TESTING


# ── Database ────
@pytest.fixture(scope="session")
def db_engine():
    """Create an in-memory SQLite engine once for the entire test session."""
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
    )
    import src.db.models  # noqa: F401 — register ORM classes

    Base.metadata.create_all(bind=engine)
    yield engine
    Base.metadata.drop_all(bind=engine)
    engine.dispose()


@pytest.fixture
def db_session(db_engine) -> Generator[Session, None, None]:
    """
    Provide a transactional session per test.
    The transaction is rolled back after each test so tests are isolated.
    """
    connection = db_engine.connect()
    transaction = connection.begin()
    session = Session(bind=connection)

    yield session

    session.close()
    transaction.rollback()
    connection.close()


# ── FastAPI test client ───
@pytest.fixture
def client(db_session) -> Generator[TestClient, None, None]:
    """
    TestClient with the DB session overridden to the test session,
    so API calls use the same in-memory DB as the test.
    """
    from src.main import create_app

    app = create_app()
    app.dependency_overrides[get_db_session] = lambda: db_session

    with TestClient(app, raise_server_exceptions=True) as c:
        yield c

    app.dependency_overrides.clear()


# ── Mock embedding model─────
@pytest.fixture
def mock_embeddings():
    """
    Returns all-zeros vectors of the configured dimension.
    Deterministic — same input always produces same output.
    """
    dim = settings.EMBEDDING_DIMENSION

    class FakeEmbedding:
        dimension = dim
        model_name = "fake-embedding-model"

        def embed(self, text: str) -> list[float]:
            # Use hash to get slightly different vectors per text
            seed = abs(hash(text)) % 1000
            return [float(seed % 10) / 10.0] * dim

        def embed_batch(self, texts: list[str]) -> list[list[float]]:
            return [self.embed(t) for t in texts]

    return FakeEmbedding()


# ── Mock LLM provider ───────
@pytest.fixture
def mock_llm():
    """Returns a canned answer regardless of the prompt."""

    class FakeLLM:
        model_name = "fake-llm"

        async def generate(self, prompt: str, system: str = "") -> str:
            return "This is a test answer generated by the fake LLM."

        async def generate_stream(self, prompt: str, system: str = "") -> AsyncIterator[str]:
            for token in ["This ", "is ", "a ", "test ", "answer."]:
                yield token

    return FakeLLM()


# ── Mock storage ────
@pytest.fixture
def mock_storage():
    """In-memory dict-based storage — no disk I/O."""

    class MemStorage:
        def __init__(self):
            self._store: dict[str, bytes] = {}

        def save(self, relative_path: str, data: bytes) -> str:
            self._store[relative_path] = data
            return relative_path

        def load(self, relative_path: str) -> bytes:
            return self._store[relative_path]

        def delete(self, relative_path: str) -> bool:
            return bool(self._store.pop(relative_path, None))

        def exists(self, relative_path: str) -> bool:
            return relative_path in self._store

        def list_files(self, prefix: str = "") -> list[str]:
            return [k for k in self._store if k.startswith(prefix)]

        def size(self, relative_path: str) -> int:
            return len(self._store.get(relative_path, b""))

    return MemStorage()


# ── Mock cache ───
@pytest.fixture
def mock_cache():
    from src.cache.manager import CacheManager
    from src.cache.memory import MemoryCache

    return CacheManager(MemoryCache(max_size=100))


# ── Mock FAISS vector store──
@pytest.fixture
def mock_vector_store():
    """In-memory vector store that accepts any vectors without needing faiss."""

    class FakeVectorStore:
        def __init__(self):
            self._data: list[tuple[str, list[float]]] = []

        def add(self, chunk_ids, embeddings):
            for cid, vec in zip(chunk_ids, embeddings, strict=False):
                self._data.append((cid, vec))

        def search(self, query_vector, top_k=5):
            ids = [d[0] for d in self._data[:top_k]]
            scores = [0.9 - i * 0.05 for i in range(len(ids))]
            return ids, scores

        def delete(self, chunk_ids):
            before = len(self._data)
            ids_set = set(chunk_ids)
            self._data = [d for d in self._data if d[0] not in ids_set]
            return before - len(self._data)

        def save(self):
            pass

        def load(self):
            pass

        def count(self):
            return len(self._data)

    return FakeVectorStore()
