"""init hitl models

Revision ID: 2ceb9121ef13
Revises: 0d2e20be1fc3
Create Date: 2026-08-23 21:52:06.943163

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ceb9121ef13"
down_revision: str | Sequence[str] | None = "0d2e20be1fc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_actions",
        sa.Column("conversation_event_id", sa.String(length=64), nullable=False),
        sa.Column("execution_id", sa.String(length=128), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("actor_type", sa.Enum("USER", "AGENT", name="actor_type"), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "GENERAL",
                "READ",
                "ANALYZE",
                "GENERATE",
                "UPDATE",
                "DELETE",
                "SEND",
                "SUBMIT",
                "EXTERNAL",
                "AGENT_CALL",
                name="action_type",
            ),
            nullable=False,
        ),
        sa.Column("tool_name", sa.String(length=255), nullable=True),
        sa.Column("target_agent_id", sa.String(length=128), nullable=True),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=256), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_APPROVAL",
                "APPROVED",
                "REJECTED",
                "EXECUTING",
                "COMPLETED",
                "FAILED",
                "EXPIRED",
                name="agent_action_status",
            ),
            nullable=False,
        ),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_event_id"],
            ["conversation_events.id"],
            name=op.f("fk_agent_actions_conversation_event_id_conversation_events"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_agent_actions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_actions")),
    )
    op.create_index(
        op.f("ix_agent_actions_action_type"), "agent_actions", ["action_type"], unique=False
    )
    op.create_index(op.f("ix_agent_actions_agent_id"), "agent_actions", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_agent_actions_conversation_event_id"),
        "agent_actions",
        ["conversation_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_actions_execution_id"), "agent_actions", ["execution_id"], unique=False
    )
    op.create_index(
        "ix_agent_actions_execution_status",
        "agent_actions",
        ["execution_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_actions_fingerprint"), "agent_actions", ["fingerprint"], unique=False
    )
    op.create_index(
        op.f("ix_agent_actions_resource_id"), "agent_actions", ["resource_id"], unique=False
    )
    op.create_index(op.f("ix_agent_actions_status"), "agent_actions", ["status"], unique=False)
    op.create_index(
        op.f("ix_agent_actions_target_agent_id"), "agent_actions", ["target_agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_actions_tenant_id"), "agent_actions", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_actions_thread_id"), "agent_actions", ["thread_id"], unique=False
    )
    op.create_index(
        "ix_agent_actions_thread_status", "agent_actions", ["thread_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_agent_actions_tool_name"), "agent_actions", ["tool_name"], unique=False
    )
    op.create_index(op.f("ix_agent_actions_user_id"), "agent_actions", ["user_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("agent_action_id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("WAITING", "APPROVED", "REJECTED", "EDITED", "EXPIRED", name="approval_status"),
            nullable=False,
        ),
        sa.Column("requested_by", sa.String(length=64), nullable=False),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column(
            "decision_type",
            sa.Enum("APPROVE", "REJECT", "EDIT", name="approval_decision_type"),
            nullable=True,
        ),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("edited_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("edited_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_action_id"],
            ["agent_actions.id"],
            name=op.f("fk_approvals_agent_action_id_agent_actions"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_approvals_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_approvals_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(
        "ix_approvals_action_status", "approvals", ["agent_action_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_approvals_agent_action_id"), "approvals", ["agent_action_id"], unique=False
    )
    op.create_index(op.f("ix_approvals_approved_by"), "approvals", ["approved_by"], unique=False)
    op.create_index(op.f("ix_approvals_expires_at"), "approvals", ["expires_at"], unique=False)
    op.create_index(
        "ix_approvals_expires_status", "approvals", ["expires_at", "status"], unique=False
    )
    op.create_index(op.f("ix_approvals_requested_by"), "approvals", ["requested_by"], unique=False)
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_requested_by"), table_name="approvals")
    op.drop_index("ix_approvals_expires_status", table_name="approvals")
    op.drop_index(op.f("ix_approvals_expires_at"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_approved_by"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_agent_action_id"), table_name="approvals")
    op.drop_index("ix_approvals_action_status", table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_agent_actions_user_id"), table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_tool_name"), table_name="agent_actions")
    op.drop_index("ix_agent_actions_thread_status", table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_thread_id"), table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_tenant_id"), table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_target_agent_id"), table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_status"), table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_resource_id"), table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_fingerprint"), table_name="agent_actions")
    op.drop_index("ix_agent_actions_execution_status", table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_execution_id"), table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_conversation_event_id"), table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_agent_id"), table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_action_type"), table_name="agent_actions")
    op.drop_table("agent_actions")
    # ### end Alembic commands ###
