"""document_id optional

Revision ID: 4e22e939d521
Revises: 8f3a1c2e7b91
Create Date: 2026-09-01 01:19:15.423995

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e22e939d521"
down_revision: str | Sequence[str] | None = "8f3a1c2e7b91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document_chunks", "document_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document_chunks", "document_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
