"""init conversation event

Revision ID: 726400d95008
Revises: 1f607177d72f
Create Date: 2026-07-23 20:05:22.995843

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "726400d95008"
down_revision: str | Sequence[str] | None = "1f607177d72f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_events",
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("parent_event_id", sa.String(length=64), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.String(length=10000), nullable=False),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_events_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_event_id"],
            ["conversation_events.id"],
            name=op.f("fk_conversation_events_parent_event_id_conversation_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_events")),
    )
    op.create_index(
        op.f("ix_conversation_events_conversation_id"),
        "conversation_events",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_events_parent_event_id"),
        "conversation_events",
        ["parent_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversation_events_parent_event_id"), table_name="conversation_events")
    op.drop_index(op.f("ix_conversation_events_conversation_id"), table_name="conversation_events")
    op.drop_table("conversation_events")
    # ### end Alembic commands ###
