"""init doc chunk embed

Revision ID: 9f0da93604ae
Revises: 4e22e939d521
Create Date: 2026-09-01 01:36:33.777786

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "9f0da93604ae"
down_revision: str | Sequence[str] | None = "4e22e939d521"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunk_embeddings",
        sa.Column("chunk_id", sa.String(), nullable=False),
        sa.Column("embedding_model", sa.String(length=255), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(dim=384), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_document_chunk_embeddings_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunk_embeddings")),
        sa.UniqueConstraint(
            "chunk_id", "embedding_model", name="uq_document_chunk_embedding_model"
        ),
    )
    op.create_index(
        "document_chunk_embeddings_embedding_idx",
        "document_chunk_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_document_chunk_embeddings_chunk_id"),
        "document_chunk_embeddings",
        ["chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunk_embeddings_embedding_model"),
        "document_chunk_embeddings",
        ["embedding_model"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_chunk_embeddings_embedding_model"), table_name="document_chunk_embeddings"
    )
    op.drop_index(
        op.f("ix_document_chunk_embeddings_chunk_id"), table_name="document_chunk_embeddings"
    )
    op.drop_index(
        "document_chunk_embeddings_embedding_idx",
        table_name="document_chunk_embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("document_chunk_embeddings")
    # ### end Alembic commands ###
