"""update document chunk

Revision ID: eaa8d6dcafcc
Revises: d5e381b7f8c7
Create Date: 2026-09-01 00:19:26.286226

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eaa8d6dcafcc"
down_revision: str | Sequence[str] | None = "d5e381b7f8c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    # ------------------------------------------------------------------
    # Move embeddings out of document_chunks.
    #
    # Embeddings now belong to DocumentChunkEmbedding.
    # ------------------------------------------------------------------

    op.drop_index(
        op.f("document_chunks_embedding_idx"),
        table_name="document_chunks",
        postgresql_ops={
            "embedding": "vector_cosine_ops",
        },
        postgresql_using="hnsw",
    )

    op.drop_column(
        "document_chunks",
        "embedding",
    )

    op.drop_column(
        "document_chunks",
        "embedding_model",
    )

    # ------------------------------------------------------------------
    # Create document_source enum before using it.
    #
    # SQLAlchemy's autogenerated migration assumes the enum already
    # exists, but PostgreSQL requires the type to be created first.
    # ------------------------------------------------------------------

    document_source_enum = postgresql.ENUM(
        "FILE",
        "WEBSITE",
        "TEXT",
        "CLOUD_STORAGE",
        name="document_source",
    )

    document_source_enum.create(
        op.get_bind(),
        checkfirst=True,
    )

    # ------------------------------------------------------------------
    # Update documents table.
    # ------------------------------------------------------------------

    op.add_column(
        "documents",
        sa.Column(
            "source_type",
            document_source_enum,
            nullable=False,
        ),
    )

    op.add_column(
        "documents",
        sa.Column(
            "source_url",
            sa.String(length=2048),
            nullable=True,
        ),
    )

    op.alter_column(
        "documents",
        "conversation_id",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )

    op.alter_column(
        "documents",
        "original_filename",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )

    op.alter_column(
        "documents",
        "filename",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )

    op.alter_column(
        "documents",
        "mime_type",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )

    op.alter_column(
        "documents",
        "size",
        existing_type=sa.INTEGER(),
        nullable=True,
    )

    op.alter_column(
        "documents",
        "storage_type",
        existing_type=postgresql.ENUM(
            "LOCAL",
            "S3",
            "AZURE_BLOB",
            "GCS",
            "MINIO",
            name="storage_type",
        ),
        nullable=True,
    )

    op.alter_column(
        "documents",
        "storage_path",
        existing_type=sa.VARCHAR(length=1024),
        nullable=True,
    )

    op.alter_column(
        "documents",
        "checksum",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )

    op.create_index(
        op.f("ix_documents_source_type"),
        "documents",
        ["source_type"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""

    # ------------------------------------------------------------------
    # Remove documents source-type changes.
    # ------------------------------------------------------------------

    op.drop_index(
        op.f("ix_documents_source_type"),
        table_name="documents",
    )

    op.alter_column(
        "documents",
        "checksum",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )

    op.alter_column(
        "documents",
        "storage_path",
        existing_type=sa.VARCHAR(length=1024),
        nullable=False,
    )

    op.alter_column(
        "documents",
        "storage_type",
        existing_type=postgresql.ENUM(
            "LOCAL",
            "S3",
            "AZURE_BLOB",
            "GCS",
            "MINIO",
            name="storage_type",
        ),
        nullable=False,
    )

    op.alter_column(
        "documents",
        "size",
        existing_type=sa.INTEGER(),
        nullable=False,
    )

    op.alter_column(
        "documents",
        "mime_type",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )

    op.alter_column(
        "documents",
        "filename",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )

    op.alter_column(
        "documents",
        "original_filename",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )

    op.alter_column(
        "documents",
        "conversation_id",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )

    op.drop_column(
        "documents",
        "source_url",
    )

    op.drop_column(
        "documents",
        "source_type",
    )

    # ------------------------------------------------------------------
    # Restore the previous embedding columns on document_chunks.
    #
    # pgvector is explicitly imported above because this migration
    # references pgvector.sqlalchemy.vector.VECTOR.
    # ------------------------------------------------------------------

    op.add_column(
        "document_chunks",
        sa.Column(
            "embedding_model",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )

    op.add_column(
        "document_chunks",
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384),
            autoincrement=False,
            nullable=True,
        ),
    )

    op.create_index(
        op.f("document_chunks_embedding_idx"),
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={
            "embedding": "vector_cosine_ops",
        },
        postgresql_using="hnsw",
    )

    # ------------------------------------------------------------------
    # Remove the document_source enum created by upgrade.
    # ------------------------------------------------------------------

    document_source_enum = postgresql.ENUM(
        "FILE",
        "WEBSITE",
        "TEXT",
        "CLOUD_STORAGE",
        name="document_source",
    )

    document_source_enum.drop(
        op.get_bind(),
        checkfirst=True,
    )
