"""Update status enum type

Revision ID: fe9044f09312
Revises: c32228f9bd67
Create Date: 2026-08-10 20:08:05.915535

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "fe9044f09312"
down_revision: str | Sequence[str] | None = "c32228f9bd67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
